### ISSUE TITLE
duplication glitch

### ISSUE THREAD

**Issue by BlackKnight683** [lt-name/GunWar_Nukkit#33]
the players who die get to keep their inventory and hence get double and triple amount of items giving an unfair advantage.... please fix this

**Comment by lt-name** [comment]
Can you describe it in detail, or record a video?

**Comment by BlackKnight683** [comment]
ok lemme describe...

i was playing a 1v1 (2 players), whenever i killed the other guy, he kept his stuff and got the default stuff(aka snowballs, arrows, bows and weapons) also! for example he had 3 arrows and 16 snowballs when he died, when he respawns he got 8 arrows and 64+16 snowballs, an extra sword and an extra bow

**Comment by lt-name** [comment]
What is the version of the plug-in?

**Comment by BlackKnight683** [comment]
latest

**Comment by lt-name** [comment]
I did not encounter this problem, I just read the code, the backpack will be cleared when the player respawns
It may also be the cause of other plugins
(Google Translate)

**Comment by BlackKnight683** [comment]
okay, i will try to disable auto inventory.... maybe thats causing the issues :D

thnx for all your supports

**Comment by BlackKnight683** [comment]
yay it works!! loved your plugin! keep up the good work :D
